### ISSUE TITLE
If a product has no variants, variant switcher does not disappear

### ISSUE THREAD

**Issue by w0sabi** [iskurbanov/shopify-next.js-tailwind#2]
When you have a product without any variants, the page still shows a variant switcher which gives the vartiant title "Title" and a variant value "Default Title". It also appears in the cart. I tried disabling it with some if conditions, but it's not a good solution. Is that the way it's supposed to be?

**Comment by iskurbanov** [comment]
I think adding an if condition is the right way to go here.
