### ISSUE TITLE
 Problem with .env when doing shopify requests by browser.

### ISSUE THREAD

**Issue by guilhermeprokisch** [iskurbanov/shopify-next.js-tailwind#4]
Hello guys.

I get stuck in the lesson 12   because the Shopify Graph Api was rejecting my requests:
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/12011070/153738064-adbd4424-d17c-461e-b4e1-0d649b86b4a3.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/12011070/153738071-8d86cd0a-7f0f-4ee8-88f5-51468be2cff6.png">

<img width="476" alt="image" src="https://user-images.githubusercontent.com/12011070/153738095-56a5614f-7f0f-469f-a625-3c296ab20306.png">

After some investigation,  I notice  the "x-shopify-storefront-access-token" was undefined. 

Next.js does not pass env variables to the browser now, except if it's prefixed with NEXT_PUBLIC_... everything works 
after I changed the env to:

NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN
NEXT_PUBLIC_SHOPIFY_ACCESS_TOKEN

**Comment by iskurbanov** [comment]
Hey thanks for that Guilherme!
